# Generated by Django 3.0.4 on 2020-06-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200626_0442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
