# Generated by Django 3.0.3 on 2020-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bulan')),
                ('harga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Harga')),
                ('produksi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produksi')),
                ('ketersediaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ketersediaan')),
                ('permintaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Permintaan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
