# Generated by Django 3.0.3 on 2020-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tahun',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tahun'),
        ),
    ]
