# Generated by Django 3.0.3 on 2020-03-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_data_tahun'),
    ]

    operations = [
        migrations.CreateModel(
            name='cbMerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bulan')),
                ('tahun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tahun')),
                ('harga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Harga')),
                ('produksi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produksi (KW)')),
                ('ketersediaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ketersediaan (TON)')),
                ('permintaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Permintaan (TON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='ketersediaan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ketersediaan (TON)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='permintaan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Permintaan (TON)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='produksi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Produksi (KW)'),
        ),
    ]
