# Generated by Django 3.0.4 on 2020-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200527_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOutputWeightCbMerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataOutputWeightCbRawit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
