# Generated by Django 3.0.4 on 2020-06-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dataoutputweightcbmerah_dataoutputweightcbrawit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMseCbMerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mse', models.CharField(blank=True, max_length=50, null=True, verbose_name='MSE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataMseCbRawit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mse', models.CharField(blank=True, max_length=50, null=True, verbose_name='MSE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
