# Generated by Django 3.0.4 on 2020-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_datamsecbmerah_datamsecbrawit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDenormalisasiCbMerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('denormalisasi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Denormalisasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataDenormalisasiCbRawit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('denormalisasi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Denormalisasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataMinMaxCbMerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('harga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Harga')),
                ('produksi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produksi (KW)')),
                ('ketersediaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ketersediaan (TON)')),
                ('permintaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Permintaan (TON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataMinMaxCbRawit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('harga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Harga')),
                ('produksi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produksi (KW)')),
                ('ketersediaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ketersediaan (TON)')),
                ('permintaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Permintaan (TON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataNewMinMaxCbMerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newmin', models.CharField(blank=True, max_length=50, null=True, verbose_name='New Min')),
                ('newmax', models.CharField(blank=True, max_length=50, null=True, verbose_name='New Max')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataNewMinMaxCbRawit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newmin', models.CharField(blank=True, max_length=50, null=True, verbose_name='New Min')),
                ('newmax', models.CharField(blank=True, max_length=50, null=True, verbose_name='New Max')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
