# Generated by Django 3.0.4 on 2020-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_datadenormalisasicbmerah_datadenormalisasicbrawit_dataminmaxcbmerah_dataminmaxcbrawit_datanewminmaxc'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadenormalisasicbmerah',
            name='hasil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hasil'),
        ),
        migrations.AddField(
            model_name='datadenormalisasicbrawit',
            name='hasil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hasil'),
        ),
    ]
