# Generated by Django 3.0.4 on 2020-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200608_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadenormalisasicbmerah',
            name='bulan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bulan'),
        ),
        migrations.AddField(
            model_name='datadenormalisasicbmerah',
            name='tahun',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tahun'),
        ),
        migrations.AddField(
            model_name='datadenormalisasicbrawit',
            name='bulan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bulan'),
        ),
        migrations.AddField(
            model_name='datadenormalisasicbrawit',
            name='tahun',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tahun'),
        ),
    ]
