# Generated by Django 3.0.4 on 2020-06-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200609_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTestingCbMerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('harga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Harga')),
                ('produksi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produksi (KW)')),
                ('ketersediaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ketersediaan (TON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataTestingCbRawit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('harga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Harga')),
                ('produksi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produksi (KW)')),
                ('ketersediaan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ketersediaan (TON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
