# Generated by Django 3.0.4 on 2020-06-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200630_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatestingcbmerah',
            name='prediksi',
        ),
        migrations.RemoveField(
            model_name='datatestingcbrawit',
            name='prediksi',
        ),
        migrations.AddField(
            model_name='datatestingcbmerah',
            name='bulan',
            field=models.CharField(max_length=50, null=True, verbose_name='Bulan'),
        ),
        migrations.AddField(
            model_name='datatestingcbmerah',
            name='permintaan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Permintaan'),
        ),
        migrations.AddField(
            model_name='datatestingcbmerah',
            name='tahun',
            field=models.CharField(max_length=50, null=True, verbose_name='Tahun'),
        ),
        migrations.AddField(
            model_name='datatestingcbrawit',
            name='bulan',
            field=models.CharField(max_length=50, null=True, verbose_name='Bulan'),
        ),
        migrations.AddField(
            model_name='datatestingcbrawit',
            name='permintaan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Permintaan'),
        ),
        migrations.AddField(
            model_name='datatestingcbrawit',
            name='tahun',
            field=models.CharField(max_length=50, null=True, verbose_name='Tahun'),
        ),
    ]
